/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectRouteImport } from './routes/select'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppLedgerRouteImport } from './routes/app.ledger'
import { Route as AppImpactRouteImport } from './routes/app.impact'
import { Route as AppDecisionsRouteImport } from './routes/app.decisions'
import { Route as AppDataRouteImport } from './routes/app.data'
import { Route as AppConnectRouteImport } from './routes/app.connect'

const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppImpactRoute = AppImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsRoute = AppDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/app/connect': typeof AppConnectRoute
  '/app/data': typeof AppDataRoute
  '/app/decisions': typeof AppDecisionsRoute
  '/app/impact': typeof AppImpactRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/app/connect': typeof AppConnectRoute
  '/app/data': typeof AppDataRoute
  '/app/decisions': typeof AppDecisionsRoute
  '/app/impact': typeof AppImpactRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/app/connect': typeof AppConnectRoute
  '/app/data': typeof AppDataRoute
  '/app/decisions': typeof AppDecisionsRoute
  '/app/impact': typeof AppImpactRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/select'
    | '/app/connect'
    | '/app/data'
    | '/app/decisions'
    | '/app/impact'
    | '/app/ledger'
    | '/app/overview'
    | '/app/reports'
    | '/app/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/select'
    | '/app/connect'
    | '/app/data'
    | '/app/decisions'
    | '/app/impact'
    | '/app/ledger'
    | '/app/overview'
    | '/app/reports'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/select'
    | '/app/connect'
    | '/app/data'
    | '/app/decisions'
    | '/app/impact'
    | '/app/ledger'
    | '/app/overview'
    | '/app/reports'
    | '/app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SelectRoute: typeof SelectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ledger': {
      id: '/app/ledger'
      path: '/ledger'
      fullPath: '/app/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/impact': {
      id: '/app/impact'
      path: '/impact'
      fullPath: '/app/impact'
      preLoaderRoute: typeof AppImpactRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/decisions': {
      id: '/app/decisions'
      path: '/decisions'
      fullPath: '/app/decisions'
      preLoaderRoute: typeof AppDecisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data': {
      id: '/app/data'
      path: '/data'
      fullPath: '/app/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connect': {
      id: '/app/connect'
      path: '/connect'
      fullPath: '/app/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConnectRoute: typeof AppConnectRoute
  AppDataRoute: typeof AppDataRoute
  AppDecisionsRoute: typeof AppDecisionsRoute
  AppImpactRoute: typeof AppImpactRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectRoute: AppConnectRoute,
  AppDataRoute: AppDataRoute,
  AppDecisionsRoute: AppDecisionsRoute,
  AppImpactRoute: AppImpactRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SelectRoute: SelectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
