/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectRouteImport } from './routes/select'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppLedgerRouteImport } from './routes/app.ledger'
import { Route as AppImpactRouteImport } from './routes/app.impact'
import { Route as AppDecisionsRouteImport } from './routes/app.decisions'
import { Route as AppDataRouteImport } from './routes/app.data'
import { Route as AppConnectRouteImport } from './routes/app.connect'
import { Route as AppLedgerIndexRouteImport } from './routes/app.ledger.index'
import { Route as AppImpactIndexRouteImport } from './routes/app.impact.index'
import { Route as AppDecisionsIndexRouteImport } from './routes/app.decisions.index'
import { Route as AppConnectIndexRouteImport } from './routes/app.connect.index'
import { Route as AppLedgerSourcesRouteImport } from './routes/app.ledger.sources'
import { Route as AppLedgerReportingRouteImport } from './routes/app.ledger.reporting'
import { Route as AppLedgerMetricsRouteImport } from './routes/app.ledger.metrics'
import { Route as AppLedgerDocumentsRouteImport } from './routes/app.ledger.documents'
import { Route as AppLedgerCsrdRouteImport } from './routes/app.ledger.csrd'
import { Route as AppLedgerCo2RouteImport } from './routes/app.ledger.co2'
import { Route as AppLedgerAuditRouteImport } from './routes/app.ledger.audit'
import { Route as AppImpactVerificationRouteImport } from './routes/app.impact.verification'
import { Route as AppImpactReportsRouteImport } from './routes/app.impact.reports'
import { Route as AppImpactProjectsRouteImport } from './routes/app.impact.projects'
import { Route as AppImpactProjectRouteImport } from './routes/app.impact.project'
import { Route as AppImpactPortfolioRouteImport } from './routes/app.impact.portfolio'
import { Route as AppImpactOrganizationsRouteImport } from './routes/app.impact.organizations'
import { Route as AppImpactCreditsRouteImport } from './routes/app.impact.credits'
import { Route as AppDecisionsScenariosRouteImport } from './routes/app.decisions.scenarios'
import { Route as AppDecisionsRiskRouteImport } from './routes/app.decisions.risk'
import { Route as AppDecisionsRecommendationsRouteImport } from './routes/app.decisions.recommendations'
import { Route as AppDecisionsNotesRouteImport } from './routes/app.decisions.notes'
import { Route as AppDecisionsDataQualityRouteImport } from './routes/app.decisions.data-quality'
import { Route as AppDecisionsAssistantRouteImport } from './routes/app.decisions.assistant'
import { Route as AppConnectSourcesRouteImport } from './routes/app.connect.sources'
import { Route as AppConnectDevicesRouteImport } from './routes/app.connect.devices'

const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppImpactRoute = AppImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsRoute = AppDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerIndexRoute = AppLedgerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLedgerRoute,
} as any)
const AppImpactIndexRoute = AppImpactIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppImpactRoute,
} as any)
const AppDecisionsIndexRoute = AppDecisionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDecisionsRoute,
} as any)
const AppConnectIndexRoute = AppConnectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConnectRoute,
} as any)
const AppLedgerSourcesRoute = AppLedgerSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppLedgerRoute,
} as any)
const AppLedgerReportingRoute = AppLedgerReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => AppLedgerRoute,
} as any)
const AppLedgerMetricsRoute = AppLedgerMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppLedgerRoute,
} as any)
const AppLedgerDocumentsRoute = AppLedgerDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppLedgerRoute,
} as any)
const AppLedgerCsrdRoute = AppLedgerCsrdRouteImport.update({
  id: '/csrd',
  path: '/csrd',
  getParentRoute: () => AppLedgerRoute,
} as any)
const AppLedgerCo2Route = AppLedgerCo2RouteImport.update({
  id: '/co2',
  path: '/co2',
  getParentRoute: () => AppLedgerRoute,
} as any)
const AppLedgerAuditRoute = AppLedgerAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppLedgerRoute,
} as any)
const AppImpactVerificationRoute = AppImpactVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AppImpactRoute,
} as any)
const AppImpactReportsRoute = AppImpactReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppImpactRoute,
} as any)
const AppImpactProjectsRoute = AppImpactProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppImpactRoute,
} as any)
const AppImpactProjectRoute = AppImpactProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => AppImpactRoute,
} as any)
const AppImpactPortfolioRoute = AppImpactPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppImpactRoute,
} as any)
const AppImpactOrganizationsRoute = AppImpactOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppImpactRoute,
} as any)
const AppImpactCreditsRoute = AppImpactCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppImpactRoute,
} as any)
const AppDecisionsScenariosRoute = AppDecisionsScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppDecisionsRoute,
} as any)
const AppDecisionsRiskRoute = AppDecisionsRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppDecisionsRoute,
} as any)
const AppDecisionsRecommendationsRoute =
  AppDecisionsRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AppDecisionsRoute,
  } as any)
const AppDecisionsNotesRoute = AppDecisionsNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppDecisionsRoute,
} as any)
const AppDecisionsDataQualityRoute = AppDecisionsDataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => AppDecisionsRoute,
} as any)
const AppDecisionsAssistantRoute = AppDecisionsAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppDecisionsRoute,
} as any)
const AppConnectSourcesRoute = AppConnectSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppConnectRoute,
} as any)
const AppConnectDevicesRoute = AppConnectDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppConnectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/app/connect': typeof AppConnectRouteWithChildren
  '/app/data': typeof AppDataRoute
  '/app/decisions': typeof AppDecisionsRouteWithChildren
  '/app/impact': typeof AppImpactRouteWithChildren
  '/app/ledger': typeof AppLedgerRouteWithChildren
  '/app/overview': typeof AppOverviewRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/connect/devices': typeof AppConnectDevicesRoute
  '/app/connect/sources': typeof AppConnectSourcesRoute
  '/app/decisions/assistant': typeof AppDecisionsAssistantRoute
  '/app/decisions/data-quality': typeof AppDecisionsDataQualityRoute
  '/app/decisions/notes': typeof AppDecisionsNotesRoute
  '/app/decisions/recommendations': typeof AppDecisionsRecommendationsRoute
  '/app/decisions/risk': typeof AppDecisionsRiskRoute
  '/app/decisions/scenarios': typeof AppDecisionsScenariosRoute
  '/app/impact/credits': typeof AppImpactCreditsRoute
  '/app/impact/organizations': typeof AppImpactOrganizationsRoute
  '/app/impact/portfolio': typeof AppImpactPortfolioRoute
  '/app/impact/project': typeof AppImpactProjectRoute
  '/app/impact/projects': typeof AppImpactProjectsRoute
  '/app/impact/reports': typeof AppImpactReportsRoute
  '/app/impact/verification': typeof AppImpactVerificationRoute
  '/app/ledger/audit': typeof AppLedgerAuditRoute
  '/app/ledger/co2': typeof AppLedgerCo2Route
  '/app/ledger/csrd': typeof AppLedgerCsrdRoute
  '/app/ledger/documents': typeof AppLedgerDocumentsRoute
  '/app/ledger/metrics': typeof AppLedgerMetricsRoute
  '/app/ledger/reporting': typeof AppLedgerReportingRoute
  '/app/ledger/sources': typeof AppLedgerSourcesRoute
  '/app/connect/': typeof AppConnectIndexRoute
  '/app/decisions/': typeof AppDecisionsIndexRoute
  '/app/impact/': typeof AppImpactIndexRoute
  '/app/ledger/': typeof AppLedgerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/app/data': typeof AppDataRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/connect/devices': typeof AppConnectDevicesRoute
  '/app/connect/sources': typeof AppConnectSourcesRoute
  '/app/decisions/assistant': typeof AppDecisionsAssistantRoute
  '/app/decisions/data-quality': typeof AppDecisionsDataQualityRoute
  '/app/decisions/notes': typeof AppDecisionsNotesRoute
  '/app/decisions/recommendations': typeof AppDecisionsRecommendationsRoute
  '/app/decisions/risk': typeof AppDecisionsRiskRoute
  '/app/decisions/scenarios': typeof AppDecisionsScenariosRoute
  '/app/impact/credits': typeof AppImpactCreditsRoute
  '/app/impact/organizations': typeof AppImpactOrganizationsRoute
  '/app/impact/portfolio': typeof AppImpactPortfolioRoute
  '/app/impact/project': typeof AppImpactProjectRoute
  '/app/impact/projects': typeof AppImpactProjectsRoute
  '/app/impact/reports': typeof AppImpactReportsRoute
  '/app/impact/verification': typeof AppImpactVerificationRoute
  '/app/ledger/audit': typeof AppLedgerAuditRoute
  '/app/ledger/co2': typeof AppLedgerCo2Route
  '/app/ledger/csrd': typeof AppLedgerCsrdRoute
  '/app/ledger/documents': typeof AppLedgerDocumentsRoute
  '/app/ledger/metrics': typeof AppLedgerMetricsRoute
  '/app/ledger/reporting': typeof AppLedgerReportingRoute
  '/app/ledger/sources': typeof AppLedgerSourcesRoute
  '/app/connect': typeof AppConnectIndexRoute
  '/app/decisions': typeof AppDecisionsIndexRoute
  '/app/impact': typeof AppImpactIndexRoute
  '/app/ledger': typeof AppLedgerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/app/connect': typeof AppConnectRouteWithChildren
  '/app/data': typeof AppDataRoute
  '/app/decisions': typeof AppDecisionsRouteWithChildren
  '/app/impact': typeof AppImpactRouteWithChildren
  '/app/ledger': typeof AppLedgerRouteWithChildren
  '/app/overview': typeof AppOverviewRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/connect/devices': typeof AppConnectDevicesRoute
  '/app/connect/sources': typeof AppConnectSourcesRoute
  '/app/decisions/assistant': typeof AppDecisionsAssistantRoute
  '/app/decisions/data-quality': typeof AppDecisionsDataQualityRoute
  '/app/decisions/notes': typeof AppDecisionsNotesRoute
  '/app/decisions/recommendations': typeof AppDecisionsRecommendationsRoute
  '/app/decisions/risk': typeof AppDecisionsRiskRoute
  '/app/decisions/scenarios': typeof AppDecisionsScenariosRoute
  '/app/impact/credits': typeof AppImpactCreditsRoute
  '/app/impact/organizations': typeof AppImpactOrganizationsRoute
  '/app/impact/portfolio': typeof AppImpactPortfolioRoute
  '/app/impact/project': typeof AppImpactProjectRoute
  '/app/impact/projects': typeof AppImpactProjectsRoute
  '/app/impact/reports': typeof AppImpactReportsRoute
  '/app/impact/verification': typeof AppImpactVerificationRoute
  '/app/ledger/audit': typeof AppLedgerAuditRoute
  '/app/ledger/co2': typeof AppLedgerCo2Route
  '/app/ledger/csrd': typeof AppLedgerCsrdRoute
  '/app/ledger/documents': typeof AppLedgerDocumentsRoute
  '/app/ledger/metrics': typeof AppLedgerMetricsRoute
  '/app/ledger/reporting': typeof AppLedgerReportingRoute
  '/app/ledger/sources': typeof AppLedgerSourcesRoute
  '/app/connect/': typeof AppConnectIndexRoute
  '/app/decisions/': typeof AppDecisionsIndexRoute
  '/app/impact/': typeof AppImpactIndexRoute
  '/app/ledger/': typeof AppLedgerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/select'
    | '/app/connect'
    | '/app/data'
    | '/app/decisions'
    | '/app/impact'
    | '/app/ledger'
    | '/app/overview'
    | '/app/reports'
    | '/app/settings'
    | '/app/connect/devices'
    | '/app/connect/sources'
    | '/app/decisions/assistant'
    | '/app/decisions/data-quality'
    | '/app/decisions/notes'
    | '/app/decisions/recommendations'
    | '/app/decisions/risk'
    | '/app/decisions/scenarios'
    | '/app/impact/credits'
    | '/app/impact/organizations'
    | '/app/impact/portfolio'
    | '/app/impact/project'
    | '/app/impact/projects'
    | '/app/impact/reports'
    | '/app/impact/verification'
    | '/app/ledger/audit'
    | '/app/ledger/co2'
    | '/app/ledger/csrd'
    | '/app/ledger/documents'
    | '/app/ledger/metrics'
    | '/app/ledger/reporting'
    | '/app/ledger/sources'
    | '/app/connect/'
    | '/app/decisions/'
    | '/app/impact/'
    | '/app/ledger/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/select'
    | '/app/data'
    | '/app/overview'
    | '/app/reports'
    | '/app/settings'
    | '/app/connect/devices'
    | '/app/connect/sources'
    | '/app/decisions/assistant'
    | '/app/decisions/data-quality'
    | '/app/decisions/notes'
    | '/app/decisions/recommendations'
    | '/app/decisions/risk'
    | '/app/decisions/scenarios'
    | '/app/impact/credits'
    | '/app/impact/organizations'
    | '/app/impact/portfolio'
    | '/app/impact/project'
    | '/app/impact/projects'
    | '/app/impact/reports'
    | '/app/impact/verification'
    | '/app/ledger/audit'
    | '/app/ledger/co2'
    | '/app/ledger/csrd'
    | '/app/ledger/documents'
    | '/app/ledger/metrics'
    | '/app/ledger/reporting'
    | '/app/ledger/sources'
    | '/app/connect'
    | '/app/decisions'
    | '/app/impact'
    | '/app/ledger'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/select'
    | '/app/connect'
    | '/app/data'
    | '/app/decisions'
    | '/app/impact'
    | '/app/ledger'
    | '/app/overview'
    | '/app/reports'
    | '/app/settings'
    | '/app/connect/devices'
    | '/app/connect/sources'
    | '/app/decisions/assistant'
    | '/app/decisions/data-quality'
    | '/app/decisions/notes'
    | '/app/decisions/recommendations'
    | '/app/decisions/risk'
    | '/app/decisions/scenarios'
    | '/app/impact/credits'
    | '/app/impact/organizations'
    | '/app/impact/portfolio'
    | '/app/impact/project'
    | '/app/impact/projects'
    | '/app/impact/reports'
    | '/app/impact/verification'
    | '/app/ledger/audit'
    | '/app/ledger/co2'
    | '/app/ledger/csrd'
    | '/app/ledger/documents'
    | '/app/ledger/metrics'
    | '/app/ledger/reporting'
    | '/app/ledger/sources'
    | '/app/connect/'
    | '/app/decisions/'
    | '/app/impact/'
    | '/app/ledger/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SelectRoute: typeof SelectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ledger': {
      id: '/app/ledger'
      path: '/ledger'
      fullPath: '/app/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/impact': {
      id: '/app/impact'
      path: '/impact'
      fullPath: '/app/impact'
      preLoaderRoute: typeof AppImpactRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/decisions': {
      id: '/app/decisions'
      path: '/decisions'
      fullPath: '/app/decisions'
      preLoaderRoute: typeof AppDecisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data': {
      id: '/app/data'
      path: '/data'
      fullPath: '/app/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connect': {
      id: '/app/connect'
      path: '/connect'
      fullPath: '/app/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ledger/': {
      id: '/app/ledger/'
      path: '/'
      fullPath: '/app/ledger/'
      preLoaderRoute: typeof AppLedgerIndexRouteImport
      parentRoute: typeof AppLedgerRoute
    }
    '/app/impact/': {
      id: '/app/impact/'
      path: '/'
      fullPath: '/app/impact/'
      preLoaderRoute: typeof AppImpactIndexRouteImport
      parentRoute: typeof AppImpactRoute
    }
    '/app/decisions/': {
      id: '/app/decisions/'
      path: '/'
      fullPath: '/app/decisions/'
      preLoaderRoute: typeof AppDecisionsIndexRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
    '/app/connect/': {
      id: '/app/connect/'
      path: '/'
      fullPath: '/app/connect/'
      preLoaderRoute: typeof AppConnectIndexRouteImport
      parentRoute: typeof AppConnectRoute
    }
    '/app/ledger/sources': {
      id: '/app/ledger/sources'
      path: '/sources'
      fullPath: '/app/ledger/sources'
      preLoaderRoute: typeof AppLedgerSourcesRouteImport
      parentRoute: typeof AppLedgerRoute
    }
    '/app/ledger/reporting': {
      id: '/app/ledger/reporting'
      path: '/reporting'
      fullPath: '/app/ledger/reporting'
      preLoaderRoute: typeof AppLedgerReportingRouteImport
      parentRoute: typeof AppLedgerRoute
    }
    '/app/ledger/metrics': {
      id: '/app/ledger/metrics'
      path: '/metrics'
      fullPath: '/app/ledger/metrics'
      preLoaderRoute: typeof AppLedgerMetricsRouteImport
      parentRoute: typeof AppLedgerRoute
    }
    '/app/ledger/documents': {
      id: '/app/ledger/documents'
      path: '/documents'
      fullPath: '/app/ledger/documents'
      preLoaderRoute: typeof AppLedgerDocumentsRouteImport
      parentRoute: typeof AppLedgerRoute
    }
    '/app/ledger/csrd': {
      id: '/app/ledger/csrd'
      path: '/csrd'
      fullPath: '/app/ledger/csrd'
      preLoaderRoute: typeof AppLedgerCsrdRouteImport
      parentRoute: typeof AppLedgerRoute
    }
    '/app/ledger/co2': {
      id: '/app/ledger/co2'
      path: '/co2'
      fullPath: '/app/ledger/co2'
      preLoaderRoute: typeof AppLedgerCo2RouteImport
      parentRoute: typeof AppLedgerRoute
    }
    '/app/ledger/audit': {
      id: '/app/ledger/audit'
      path: '/audit'
      fullPath: '/app/ledger/audit'
      preLoaderRoute: typeof AppLedgerAuditRouteImport
      parentRoute: typeof AppLedgerRoute
    }
    '/app/impact/verification': {
      id: '/app/impact/verification'
      path: '/verification'
      fullPath: '/app/impact/verification'
      preLoaderRoute: typeof AppImpactVerificationRouteImport
      parentRoute: typeof AppImpactRoute
    }
    '/app/impact/reports': {
      id: '/app/impact/reports'
      path: '/reports'
      fullPath: '/app/impact/reports'
      preLoaderRoute: typeof AppImpactReportsRouteImport
      parentRoute: typeof AppImpactRoute
    }
    '/app/impact/projects': {
      id: '/app/impact/projects'
      path: '/projects'
      fullPath: '/app/impact/projects'
      preLoaderRoute: typeof AppImpactProjectsRouteImport
      parentRoute: typeof AppImpactRoute
    }
    '/app/impact/project': {
      id: '/app/impact/project'
      path: '/project'
      fullPath: '/app/impact/project'
      preLoaderRoute: typeof AppImpactProjectRouteImport
      parentRoute: typeof AppImpactRoute
    }
    '/app/impact/portfolio': {
      id: '/app/impact/portfolio'
      path: '/portfolio'
      fullPath: '/app/impact/portfolio'
      preLoaderRoute: typeof AppImpactPortfolioRouteImport
      parentRoute: typeof AppImpactRoute
    }
    '/app/impact/organizations': {
      id: '/app/impact/organizations'
      path: '/organizations'
      fullPath: '/app/impact/organizations'
      preLoaderRoute: typeof AppImpactOrganizationsRouteImport
      parentRoute: typeof AppImpactRoute
    }
    '/app/impact/credits': {
      id: '/app/impact/credits'
      path: '/credits'
      fullPath: '/app/impact/credits'
      preLoaderRoute: typeof AppImpactCreditsRouteImport
      parentRoute: typeof AppImpactRoute
    }
    '/app/decisions/scenarios': {
      id: '/app/decisions/scenarios'
      path: '/scenarios'
      fullPath: '/app/decisions/scenarios'
      preLoaderRoute: typeof AppDecisionsScenariosRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
    '/app/decisions/risk': {
      id: '/app/decisions/risk'
      path: '/risk'
      fullPath: '/app/decisions/risk'
      preLoaderRoute: typeof AppDecisionsRiskRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
    '/app/decisions/recommendations': {
      id: '/app/decisions/recommendations'
      path: '/recommendations'
      fullPath: '/app/decisions/recommendations'
      preLoaderRoute: typeof AppDecisionsRecommendationsRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
    '/app/decisions/notes': {
      id: '/app/decisions/notes'
      path: '/notes'
      fullPath: '/app/decisions/notes'
      preLoaderRoute: typeof AppDecisionsNotesRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
    '/app/decisions/data-quality': {
      id: '/app/decisions/data-quality'
      path: '/data-quality'
      fullPath: '/app/decisions/data-quality'
      preLoaderRoute: typeof AppDecisionsDataQualityRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
    '/app/decisions/assistant': {
      id: '/app/decisions/assistant'
      path: '/assistant'
      fullPath: '/app/decisions/assistant'
      preLoaderRoute: typeof AppDecisionsAssistantRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
    '/app/connect/sources': {
      id: '/app/connect/sources'
      path: '/sources'
      fullPath: '/app/connect/sources'
      preLoaderRoute: typeof AppConnectSourcesRouteImport
      parentRoute: typeof AppConnectRoute
    }
    '/app/connect/devices': {
      id: '/app/connect/devices'
      path: '/devices'
      fullPath: '/app/connect/devices'
      preLoaderRoute: typeof AppConnectDevicesRouteImport
      parentRoute: typeof AppConnectRoute
    }
  }
}

interface AppConnectRouteChildren {
  AppConnectDevicesRoute: typeof AppConnectDevicesRoute
  AppConnectSourcesRoute: typeof AppConnectSourcesRoute
  AppConnectIndexRoute: typeof AppConnectIndexRoute
}

const AppConnectRouteChildren: AppConnectRouteChildren = {
  AppConnectDevicesRoute: AppConnectDevicesRoute,
  AppConnectSourcesRoute: AppConnectSourcesRoute,
  AppConnectIndexRoute: AppConnectIndexRoute,
}

const AppConnectRouteWithChildren = AppConnectRoute._addFileChildren(
  AppConnectRouteChildren,
)

interface AppDecisionsRouteChildren {
  AppDecisionsAssistantRoute: typeof AppDecisionsAssistantRoute
  AppDecisionsDataQualityRoute: typeof AppDecisionsDataQualityRoute
  AppDecisionsNotesRoute: typeof AppDecisionsNotesRoute
  AppDecisionsRecommendationsRoute: typeof AppDecisionsRecommendationsRoute
  AppDecisionsRiskRoute: typeof AppDecisionsRiskRoute
  AppDecisionsScenariosRoute: typeof AppDecisionsScenariosRoute
  AppDecisionsIndexRoute: typeof AppDecisionsIndexRoute
}

const AppDecisionsRouteChildren: AppDecisionsRouteChildren = {
  AppDecisionsAssistantRoute: AppDecisionsAssistantRoute,
  AppDecisionsDataQualityRoute: AppDecisionsDataQualityRoute,
  AppDecisionsNotesRoute: AppDecisionsNotesRoute,
  AppDecisionsRecommendationsRoute: AppDecisionsRecommendationsRoute,
  AppDecisionsRiskRoute: AppDecisionsRiskRoute,
  AppDecisionsScenariosRoute: AppDecisionsScenariosRoute,
  AppDecisionsIndexRoute: AppDecisionsIndexRoute,
}

const AppDecisionsRouteWithChildren = AppDecisionsRoute._addFileChildren(
  AppDecisionsRouteChildren,
)

interface AppImpactRouteChildren {
  AppImpactCreditsRoute: typeof AppImpactCreditsRoute
  AppImpactOrganizationsRoute: typeof AppImpactOrganizationsRoute
  AppImpactPortfolioRoute: typeof AppImpactPortfolioRoute
  AppImpactProjectRoute: typeof AppImpactProjectRoute
  AppImpactProjectsRoute: typeof AppImpactProjectsRoute
  AppImpactReportsRoute: typeof AppImpactReportsRoute
  AppImpactVerificationRoute: typeof AppImpactVerificationRoute
  AppImpactIndexRoute: typeof AppImpactIndexRoute
}

const AppImpactRouteChildren: AppImpactRouteChildren = {
  AppImpactCreditsRoute: AppImpactCreditsRoute,
  AppImpactOrganizationsRoute: AppImpactOrganizationsRoute,
  AppImpactPortfolioRoute: AppImpactPortfolioRoute,
  AppImpactProjectRoute: AppImpactProjectRoute,
  AppImpactProjectsRoute: AppImpactProjectsRoute,
  AppImpactReportsRoute: AppImpactReportsRoute,
  AppImpactVerificationRoute: AppImpactVerificationRoute,
  AppImpactIndexRoute: AppImpactIndexRoute,
}

const AppImpactRouteWithChildren = AppImpactRoute._addFileChildren(
  AppImpactRouteChildren,
)

interface AppLedgerRouteChildren {
  AppLedgerAuditRoute: typeof AppLedgerAuditRoute
  AppLedgerCo2Route: typeof AppLedgerCo2Route
  AppLedgerCsrdRoute: typeof AppLedgerCsrdRoute
  AppLedgerDocumentsRoute: typeof AppLedgerDocumentsRoute
  AppLedgerMetricsRoute: typeof AppLedgerMetricsRoute
  AppLedgerReportingRoute: typeof AppLedgerReportingRoute
  AppLedgerSourcesRoute: typeof AppLedgerSourcesRoute
  AppLedgerIndexRoute: typeof AppLedgerIndexRoute
}

const AppLedgerRouteChildren: AppLedgerRouteChildren = {
  AppLedgerAuditRoute: AppLedgerAuditRoute,
  AppLedgerCo2Route: AppLedgerCo2Route,
  AppLedgerCsrdRoute: AppLedgerCsrdRoute,
  AppLedgerDocumentsRoute: AppLedgerDocumentsRoute,
  AppLedgerMetricsRoute: AppLedgerMetricsRoute,
  AppLedgerReportingRoute: AppLedgerReportingRoute,
  AppLedgerSourcesRoute: AppLedgerSourcesRoute,
  AppLedgerIndexRoute: AppLedgerIndexRoute,
}

const AppLedgerRouteWithChildren = AppLedgerRoute._addFileChildren(
  AppLedgerRouteChildren,
)

interface AppRouteChildren {
  AppConnectRoute: typeof AppConnectRouteWithChildren
  AppDataRoute: typeof AppDataRoute
  AppDecisionsRoute: typeof AppDecisionsRouteWithChildren
  AppImpactRoute: typeof AppImpactRouteWithChildren
  AppLedgerRoute: typeof AppLedgerRouteWithChildren
  AppOverviewRoute: typeof AppOverviewRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectRoute: AppConnectRouteWithChildren,
  AppDataRoute: AppDataRoute,
  AppDecisionsRoute: AppDecisionsRouteWithChildren,
  AppImpactRoute: AppImpactRouteWithChildren,
  AppLedgerRoute: AppLedgerRouteWithChildren,
  AppOverviewRoute: AppOverviewRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SelectRoute: SelectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
