/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectRouteImport } from './routes/select'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppLedgerRouteImport } from './routes/app.ledger'
import { Route as AppImpactRouteImport } from './routes/app.impact'
import { Route as AppDecisionsRouteImport } from './routes/app.decisions'
import { Route as AppDataRouteImport } from './routes/app.data'
import { Route as AppConnectRouteImport } from './routes/app.connect'
import { Route as AppDecisionsIndexRouteImport } from './routes/app.decisions.index'
import { Route as AppDecisionsScenariosRouteImport } from './routes/app.decisions.scenarios'
import { Route as AppDecisionsRiskRouteImport } from './routes/app.decisions.risk'
import { Route as AppDecisionsRecommendationsRouteImport } from './routes/app.decisions.recommendations'
import { Route as AppDecisionsNotesRouteImport } from './routes/app.decisions.notes'
import { Route as AppDecisionsDataQualityRouteImport } from './routes/app.decisions.data-quality'
import { Route as AppDecisionsAssistantRouteImport } from './routes/app.decisions.assistant'

const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppImpactRoute = AppImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsRoute = AppDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsIndexRoute = AppDecisionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDecisionsRoute,
} as any)
const AppDecisionsScenariosRoute = AppDecisionsScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppDecisionsRoute,
} as any)
const AppDecisionsRiskRoute = AppDecisionsRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppDecisionsRoute,
} as any)
const AppDecisionsRecommendationsRoute =
  AppDecisionsRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AppDecisionsRoute,
  } as any)
const AppDecisionsNotesRoute = AppDecisionsNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppDecisionsRoute,
} as any)
const AppDecisionsDataQualityRoute = AppDecisionsDataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => AppDecisionsRoute,
} as any)
const AppDecisionsAssistantRoute = AppDecisionsAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppDecisionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/app/connect': typeof AppConnectRoute
  '/app/data': typeof AppDataRoute
  '/app/decisions': typeof AppDecisionsRouteWithChildren
  '/app/impact': typeof AppImpactRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/decisions/assistant': typeof AppDecisionsAssistantRoute
  '/app/decisions/data-quality': typeof AppDecisionsDataQualityRoute
  '/app/decisions/notes': typeof AppDecisionsNotesRoute
  '/app/decisions/recommendations': typeof AppDecisionsRecommendationsRoute
  '/app/decisions/risk': typeof AppDecisionsRiskRoute
  '/app/decisions/scenarios': typeof AppDecisionsScenariosRoute
  '/app/decisions/': typeof AppDecisionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/app/connect': typeof AppConnectRoute
  '/app/data': typeof AppDataRoute
  '/app/impact': typeof AppImpactRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/decisions/assistant': typeof AppDecisionsAssistantRoute
  '/app/decisions/data-quality': typeof AppDecisionsDataQualityRoute
  '/app/decisions/notes': typeof AppDecisionsNotesRoute
  '/app/decisions/recommendations': typeof AppDecisionsRecommendationsRoute
  '/app/decisions/risk': typeof AppDecisionsRiskRoute
  '/app/decisions/scenarios': typeof AppDecisionsScenariosRoute
  '/app/decisions': typeof AppDecisionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/select': typeof SelectRoute
  '/app/connect': typeof AppConnectRoute
  '/app/data': typeof AppDataRoute
  '/app/decisions': typeof AppDecisionsRouteWithChildren
  '/app/impact': typeof AppImpactRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/decisions/assistant': typeof AppDecisionsAssistantRoute
  '/app/decisions/data-quality': typeof AppDecisionsDataQualityRoute
  '/app/decisions/notes': typeof AppDecisionsNotesRoute
  '/app/decisions/recommendations': typeof AppDecisionsRecommendationsRoute
  '/app/decisions/risk': typeof AppDecisionsRiskRoute
  '/app/decisions/scenarios': typeof AppDecisionsScenariosRoute
  '/app/decisions/': typeof AppDecisionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/select'
    | '/app/connect'
    | '/app/data'
    | '/app/decisions'
    | '/app/impact'
    | '/app/ledger'
    | '/app/overview'
    | '/app/reports'
    | '/app/settings'
    | '/app/decisions/assistant'
    | '/app/decisions/data-quality'
    | '/app/decisions/notes'
    | '/app/decisions/recommendations'
    | '/app/decisions/risk'
    | '/app/decisions/scenarios'
    | '/app/decisions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/select'
    | '/app/connect'
    | '/app/data'
    | '/app/impact'
    | '/app/ledger'
    | '/app/overview'
    | '/app/reports'
    | '/app/settings'
    | '/app/decisions/assistant'
    | '/app/decisions/data-quality'
    | '/app/decisions/notes'
    | '/app/decisions/recommendations'
    | '/app/decisions/risk'
    | '/app/decisions/scenarios'
    | '/app/decisions'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/select'
    | '/app/connect'
    | '/app/data'
    | '/app/decisions'
    | '/app/impact'
    | '/app/ledger'
    | '/app/overview'
    | '/app/reports'
    | '/app/settings'
    | '/app/decisions/assistant'
    | '/app/decisions/data-quality'
    | '/app/decisions/notes'
    | '/app/decisions/recommendations'
    | '/app/decisions/risk'
    | '/app/decisions/scenarios'
    | '/app/decisions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SelectRoute: typeof SelectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ledger': {
      id: '/app/ledger'
      path: '/ledger'
      fullPath: '/app/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/impact': {
      id: '/app/impact'
      path: '/impact'
      fullPath: '/app/impact'
      preLoaderRoute: typeof AppImpactRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/decisions': {
      id: '/app/decisions'
      path: '/decisions'
      fullPath: '/app/decisions'
      preLoaderRoute: typeof AppDecisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data': {
      id: '/app/data'
      path: '/data'
      fullPath: '/app/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connect': {
      id: '/app/connect'
      path: '/connect'
      fullPath: '/app/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/decisions/': {
      id: '/app/decisions/'
      path: '/'
      fullPath: '/app/decisions/'
      preLoaderRoute: typeof AppDecisionsIndexRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
    '/app/decisions/scenarios': {
      id: '/app/decisions/scenarios'
      path: '/scenarios'
      fullPath: '/app/decisions/scenarios'
      preLoaderRoute: typeof AppDecisionsScenariosRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
    '/app/decisions/risk': {
      id: '/app/decisions/risk'
      path: '/risk'
      fullPath: '/app/decisions/risk'
      preLoaderRoute: typeof AppDecisionsRiskRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
    '/app/decisions/recommendations': {
      id: '/app/decisions/recommendations'
      path: '/recommendations'
      fullPath: '/app/decisions/recommendations'
      preLoaderRoute: typeof AppDecisionsRecommendationsRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
    '/app/decisions/notes': {
      id: '/app/decisions/notes'
      path: '/notes'
      fullPath: '/app/decisions/notes'
      preLoaderRoute: typeof AppDecisionsNotesRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
    '/app/decisions/data-quality': {
      id: '/app/decisions/data-quality'
      path: '/data-quality'
      fullPath: '/app/decisions/data-quality'
      preLoaderRoute: typeof AppDecisionsDataQualityRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
    '/app/decisions/assistant': {
      id: '/app/decisions/assistant'
      path: '/assistant'
      fullPath: '/app/decisions/assistant'
      preLoaderRoute: typeof AppDecisionsAssistantRouteImport
      parentRoute: typeof AppDecisionsRoute
    }
  }
}

interface AppDecisionsRouteChildren {
  AppDecisionsAssistantRoute: typeof AppDecisionsAssistantRoute
  AppDecisionsDataQualityRoute: typeof AppDecisionsDataQualityRoute
  AppDecisionsNotesRoute: typeof AppDecisionsNotesRoute
  AppDecisionsRecommendationsRoute: typeof AppDecisionsRecommendationsRoute
  AppDecisionsRiskRoute: typeof AppDecisionsRiskRoute
  AppDecisionsScenariosRoute: typeof AppDecisionsScenariosRoute
  AppDecisionsIndexRoute: typeof AppDecisionsIndexRoute
}

const AppDecisionsRouteChildren: AppDecisionsRouteChildren = {
  AppDecisionsAssistantRoute: AppDecisionsAssistantRoute,
  AppDecisionsDataQualityRoute: AppDecisionsDataQualityRoute,
  AppDecisionsNotesRoute: AppDecisionsNotesRoute,
  AppDecisionsRecommendationsRoute: AppDecisionsRecommendationsRoute,
  AppDecisionsRiskRoute: AppDecisionsRiskRoute,
  AppDecisionsScenariosRoute: AppDecisionsScenariosRoute,
  AppDecisionsIndexRoute: AppDecisionsIndexRoute,
}

const AppDecisionsRouteWithChildren = AppDecisionsRoute._addFileChildren(
  AppDecisionsRouteChildren,
)

interface AppRouteChildren {
  AppConnectRoute: typeof AppConnectRoute
  AppDataRoute: typeof AppDataRoute
  AppDecisionsRoute: typeof AppDecisionsRouteWithChildren
  AppImpactRoute: typeof AppImpactRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectRoute: AppConnectRoute,
  AppDataRoute: AppDataRoute,
  AppDecisionsRoute: AppDecisionsRouteWithChildren,
  AppImpactRoute: AppImpactRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SelectRoute: SelectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
