// This file is automatically generated. Do not edit it directly.
import { requireSupabaseClient } from "@/lib/supabase/client";
import type { Database } from "./types";
import type { SupabaseClient } from "@supabase/supabase-js";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
// This compatibility proxy preserves the generated module's fail-fast API,
// while all browser call sites share the canonical client and GoTrue session.
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop) {
    const client = requireSupabaseClient();
    return Reflect.get(client, prop, client);
  },
});
